name: GitHub Actions Demo
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run : |
          docker build -t hamstershare/hamster-portal:latest .
          docker push hamstershare/hamster-portal:latest
  deploy:
    name: deploy
    needs:
      - docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy portal
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HAMSTER_SERVER_HOST }}
          username: ${{ secrets.HAMSTER_SERVER_USERNAME }}
          key: ${{ secrets.HAMSTER_SERVER_KEY }}
          port: ${{ secrets.HAMSTER_SERVER_PORT }}
          script: |
            cd /root/hamster_portal
            docker images | grep hamstershare/hamster-portal | grep latest | awk '{print "docker tag " $3 " hamstershare/hamster-portal:rollback"}' | sh
            docker compose pull
            docker compose up -d
            docker images | grep hamstershare/hamster-portal | grep none | awk '{print "docker rmi " $3}'| sh
