name: GitHub Actions Demo
on: [push]
jobs:
  docker-build:
    if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run : |
          docker build -t hamstershare/hamster-portal:latest .
          docker push hamstershare/hamster-portal:latest
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: deploy
    needs:
      - docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy portal
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd /root/hamster_portal
            docker compose pull
            docker compose up -d
