name: GitHub Actions Demo
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run : |
          docker build -t hamstershare/hamster-portal:develop .
          docker push hamstershare/hamster-portal:develop
  deploy:
    name: deploy
    needs:
      - docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.TEST_KUBE_CONFIG }}
          kubectl-version: v1.26.1
      - run: |
          echo $GITHUB_ACTION
          kubectl get pods
