name: Hamster Protal Test
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: hamstershare/hamster-portal

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: deploy
    needs:
      - docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.TEST_KUBE_CONFIG }}
          kubectl-version: v1.26.1
      - run: |
          env
          kubectl get pods
